packages:
  - apps/*

catalog:
  '@biomejs/biome': 2.3.14

ignoredBuiltDependencies:
  - '@firebase/util'
  - protobufjs
  - re2

onlyBuiltDependencies:
  - '@prisma/engines'
  - '@sentry/cli'
  - esbuild
  - msw
  - prisma
  - sharp
  - unrs-resolver
