# .github/ISSUE_TEMPLATE/docs.yml

name: "docs"
description: "ドキュメント作成・整備"
title: "docs: "
labels: ["type: docs"]
assignees: []

body:
  - type: input
    id: summary
    attributes:
      label: 概要
      description: "～によって～を可能にするか、短く明確に"
      placeholder: "検索設計ガイドを整備して、チーム全員が検索ロジックの意図を共有できるようにする"
    validations:
      required: true

  - type: textarea
    id: relations
    attributes:
      label: 関連
      description: "関係するissue・PR・仕様書など"
      placeholder: |
        - PR
          - #34
      value: |
        - ドキュメント
          - []()
    validations:
      required: false

  - type: textarea
    id: goal
    attributes:
      label: 目的
      description: "何を解決し、どう良くなるか"
      placeholder: |
        - 課題：API仕様が散在しており、設計判断に時間がかかっている
        - 経緯：設計レビューや実装時に参照先が分かれ、認識差分が繰り返し発生している
        - 期待：単一の仕様書に統合して、参照とレビューを容易にする
      value: |
        - 課題：
        - 経緯：
        - 期待：
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: 受け入れ条件
      description: |
        - [docs/CONTRIBUTING.md「6. DoD（完了の定義）」](https://github.com/i1wawa/cococoffee/blob/main/docs/CONTRIBUTING.md#6-dod完了の定義)の他にあれば
        - Gherkinステップ（Given 条件/When 操作/Then 結果）など
      placeholder: |
        - 主要章立て（目的／設計方針／API一覧）が揃っている
        - 関連ドキュメント（#52, #53）へのリンクが正しく設定
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: スコープ
      description: "やる・やらないの境界を明示"
      placeholder: |
        - 対象：フロントエンド設計書およびAPI仕様の整備
        - 含めない範囲：インフラ構成図、CI設定の説明
      value: |
        - 対象：
        - 含めない範囲：
    validations:
      required: false

  - type: textarea
    id: risk_categories
    attributes:
      label: リスク種類
      description: "種類ごとに該当有無をチェック（☐／☒）"
      placeholder: |
        |該当|種類|観点例|
        |---|---|---|
        |☐|セキュリティ|認証・セッション・権限・入出力・暗号・通信・ログ・設定・依存|
        |☐|プライバシー・法務||
        |☐|ライセンス||
        |☐|パフォーマンス|レイテンシ・容量・実行時間|
        |☐|互換性|環境・依存・DB・API・テスト|
        |☐|費用・サステナビリティ||
        |☐|UX・アクセシビリティ|一貫性・期待整合・認知量・操作性・デザイン性・倫理|
        |☐|DevEx|解析容易性・変更容易性・テスト容易性・情報整合性・メトリクス・ログ・作業量|
        |☐|該当なし||
      value: |
        |該当|種類|観点例|
        |---|---|---|
        |☐|セキュリティ|認証・セッション・権限・入出力・暗号・通信・ログ・設定・依存|
        |☐|プライバシー・法務||
        |☐|ライセンス||
        |☐|パフォーマンス|レイテンシ・容量・実行時間|
        |☐|互換性|環境・依存・DB・API・テスト|
        |☐|費用・サステナビリティ||
        |☐|UX・アクセシビリティ|一貫性・期待整合・認知量・操作性・デザイン性・倫理|
        |☐|DevEx|解析容易性・変更容易性・テスト容易性・情報整合性・メトリクス・ログ・作業量|
        |☐|該当なし||
    validations:
      required: true

  - type: textarea
    id: risk_detail
    attributes:
      label: リスク詳細
      description: "与え得るリスクの詳細"
      placeholder: |
        - セキュリティ：記載情報から認証情報・シークレット漏洩のリスク
        - プライバシー：記載情報から個人情報漏洩のリスク
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ※以下を満たすこと
        - [docs/CONTRIBUTING.md「4. DoR（着手可能の定義）」](https://github.com/i1wawa/cococoffee/blob/main/docs/CONTRIBUTING.md#4-dor着手可能の定義)
        - [docs/CONTRIBUTING.md「6. DoD（完了の定義）」](https://github.com/i1wawa/cococoffee/blob/main/docs/CONTRIBUTING.md#6-dod完了の定義)
